# Generated by Django 4.0 on 2021-12-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aumento', models.IntegerField(choices=[(1, 'Porcentaje'), (2, 'Suma Fija')], default=1)),
                ('tipo_calculo', models.IntegerField(choices=[(1, 'basico'), (2, 'suplemento1'), (3, 'suplemento2'), (4, 'sumafija1'), (5, 'sumafija2'), (6, 'sumafija3')], default=1)),
                ('regla', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('has_modulo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'aumentos',
                'ordering': ['orden'],
            },
        ),
    ]
