# Generated by Django 4.0 on 2021-12-26 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aumentos', '0001_initial'),
        ('cuadricula', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('cuadriculamovimiento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cuadricula.cuadriculamovimiento')),
                ('tipo_movimiento', models.IntegerField(choices=[(1, 'Aumento'), (2, 'Alta'), (3, 'Baja')], default=1)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('is_close', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'db_table': 'movimientos',
                'ordering': ['orden'],
                'managed': True,
            },
            bases=('cuadricula.cuadriculamovimiento',),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('nombre', models.CharField(default=None, max_length=60, null=True)),
                ('descripcion', models.CharField(default=None, max_length=120, null=True)),
                ('fecha_limite', models.DateField(null=True)),
                ('fecha_hiscar', models.DateField(null=True)),
                ('is_close', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to='auth.user')),
                ('eliminator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_eliminator', to='auth.user')),
                ('modifier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modifier', to='auth.user')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'managed': True,
            },
        ),
    ]
