# Generated by Django 4.0 on 2021-12-26 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('text', models.TextField(blank=True, default='', null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuadriculaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(blank=True, default=None, null=True)),
                ('deleted', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=120)),
                ('periodo_dd', models.DateField(db_index=True, default=None, null=True)),
                ('periodo_ht', models.DateField(db_index=True, default=None, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_creator', to='auth.user')),
                ('eliminator', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_eliminator', to='auth.user')),
                ('modifier', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_modifier', to='auth.user')),
            ],
            options={
                'db_table': 'cuadriculas',
                'managed': True,
            },
        ),
    ]
