# Generated by Django 4.0 on 2021-12-26 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuadricula', '0001_initial'),
        ('aumentos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuadriculamovimiento',
            name='proyecto',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='aumentos.proyecto'),
        ),
    ]
