version: '3.5'

volumes:
  postgresql-data-siliq:

networks:
  default:
    external:
      name: ips-gba-gov-ar

services:
  postgres-siliq:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data-siliq:/var/lib/postgresql/data
    env_file:
      - prod.env
    restart: unless-stopped

  app-siliq:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    command: [
        "sh", "-c",
        "pip install debugpy --upgrade -t /tmp &&
        python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678
        manage.py runserver 0.0.0.0:80 --nothreading --noreload"]
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.debug-vscode
    env_file:
      - prod.env
    ports:
      - 5678:5678
      - 80:80
    restart: unless-stopped

  celery_worker-siliq:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-celery
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.debug
    command: sh -c "
      celery
      -A project
      worker
      -l info
      --pidfile=celery.pid"

  celery_beat-siliq:
    build:
      context: .
      dockerfile: Dockerfile
      target: app-celery
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings.debug
    command: sh -c "celery
      -A project beat
      -l info
      --scheduler django_celery_beat.schedulers:DatabaseScheduler
      --pidfile=beat.pid"
