name: Django lint and test.

on:
  pull_request:
    branches:
      - production

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.2
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
        SECRET_KEY : ${{ secrets.SECRET_KEY  }}
        DJANGO_SETTINGS_MODULE : project.settings.production

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/prod.txt
    - name: Run migrations
      run: python manage.py migrate
    - name: Django Testing
      run: |
        python3 manage.py test
